name: pr-check
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 获取信息
      id: get_info
      run: echo "repository_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v3
    - name: 安装java8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: 构建
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
    - name: 收集构建文件
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.get_info.outputs.repository_name }}-Pr_check-Build-${{ github.run_number}}
        path: staging